#!/usr/bin/env bash
# If 9 say hi and then Holberton School

i=1
while [ $i -le 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Holberton School"
        echo "Hi"
    else
        echo "Holberton School"
    fi
    ((i++))
done
